from .add import add
from .compose import compose
from .curry import curry
from .equal import equal
from .filter import filter
from .getattr import getattr
from .getitem import getitem
from .isinstance import isinstance
from .map import map
from .reduce import reduce
