from .all_pass import all_pass
from .and_func import and_func
from .any_pass import any_pass
from .both import both
from .complement import complement
from .either import either
from .if_else import if_else
from .not_func import not_func
from .or_func import or_func
